# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lucas/VivadoProjects/direct_digital_synthesizer/direct_digital_synthesizer.srcs/sources_1/ip/single_port_ROM/single_port_ROM.xci
# IP: The module: 'single_port_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lucas/VivadoProjects/direct_digital_synthesizer/direct_digital_synthesizer.gen/sources_1/ip/single_port_ROM/single_port_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'single_port_ROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/lucas/VivadoProjects/direct_digital_synthesizer/direct_digital_synthesizer.srcs/sources_1/ip/single_port_ROM/single_port_ROM.xci
# IP: The module: 'single_port_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lucas/VivadoProjects/direct_digital_synthesizer/direct_digital_synthesizer.gen/sources_1/ip/single_port_ROM/single_port_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'single_port_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
